# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json

name: "additional_seq_prepare"
description: BRC/Ensembl metazoa pipeline. Preparation of genome data loading files (Fasta, GFF3, JSON) for new sequence(s) to existing species databases.  
keywords:
  - fasta
  - gff3
  - json
  - schema
  - validate
  - genbank
  - annotation
  - genome
  - mitochondrion
  - seq-region
modules:
  - download/download_genbank
  - files/publish_output
  - genbank/extract_from_gb
  - gff3/gff3_validation
  - gff3/process_gff3
  - manifest/integrity
  - manifest/manifest_maker
  - manifest/manifest_stats
  - schema/check_json_schema
input:
  - accession:
      type: string
      description: |
        MANDATORY param. A mitochondrion Genbank accession of mt genome sequence being added. e.g. NC_XXXXXXX.X
  - prefix:
      type: string
      description: |
        MANDATORY param. A prefix name/identifier added to all genes in order to ensure gene ids are unique.
  - production_name:
      type: string
      description: |
        MANDATORY param. Ensembl 'production_name' assigned to species having sequence(s) added.
output:
  - dna:
      type: file
      description: |
        Fasta file containing nucleotide sequence(s) added during processing.
      pattern: "dna.fasta"
  - functional_annotation:
      type: file
      description: |
        JSON file containing the metadata for gene models
      pattern: "functional_annotation.json"
  - gene_models:
      type: file
      description: |
        GFF3 format file covering all seq_regions and the gene feature associated with the added sequence.
      pattern: "gene_models.gff3"
  - genome:
      type: file
      description: |
        JSON file describing species name, assembly and accession related information for all added sequences.
      pattern: "genome.json"
  - manifest:
      type: file
      description: |
        Manifest json file listing all generated output files in main output folder and associated md5 checksums.
      pattern: "manifest.json"
  - pep:
      type: file
      description: |
        Fasta file containing peptide sequences added during processing.
      pattern: "pep.fasta"
  - seq_region:
      type: file
      description: |
        JSON file describing added sequence(s), sequence length(s), coordinate level(s), codon table(s), sequence topology etc.
      pattern: "seq_region.json"
  - stats:
      type: file
      description: |
        General stats on gene amendments and summary of coord_system and seq_region alterations.
      pattern: "stats.txt"
authors:
  - Ensembl
