# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

site_name: Ensembl-GenomIO
site_url: "https://ensembl.github.io/ensembl-genomio"
repo_url: "https://github.com/Ensembl/ensembl-genomio"
repo_name: "Ensembl-GenomIO"
copyright: "Copyright &copy; [2016-<script>document.write(new Date().getFullYear())</script>] EMBL-European Bioinformatics Institute"

theme:
  name: "material"
  logo: img/ebang.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: fontawesome/solid/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: fontawesome/regular/lightbulb
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true

plugins:
- search
- gen-files:
     scripts:
     - docs/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    handlers:
      python:
        options:
          inherited_members: true
          members: true
          show_root_heading: true
          show_source: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true

nav:
  - Home: index.md
  - Usage: usage.md
  - Install: install.md
  - Code Reference: reference/
  - Running Nextflow: nextflow.md
  - Ensembl-Genomio Pipelines: pipelines.md
