# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# License-related part of the Ensembl/ensembl-genomio CI/CD pipeline

# A generic job to be used by all License jobs with the "extends" mechanism
# (https://docs.gitlab.com/ee/ci/yaml/#extends)


variables:
  # https://docs.gitlab.com/ee/user/namespace/  
  CONTAINER_IMAGE_NAME: datasets-cli
  DATASETS_DIR: containers/docker/datasets-cli
  SCRIPTS_DIR: scripts
  
  # GITLAB:
  GITLAB_PROJECT: vectorbase
  GITLAB_REPO: ensembl-genomio
  GITLAB_DOCKER_IMAGE: $GITLAB_PROJECT/$GITLAB_REPO/$CONTAINER_IMAGE_NAME
  
  # DOCKERHUB:
  DOCKERHUB_PROJECT: ensemblorg
  DHUB_DOCKER_IMAGE: $DOCKERHUB_PROJECT/$CONTAINER_IMAGE_NAME
  DHUB_REG_URL: registry.hub.docker.com


datasets_docker_build:
  # only:
  #   variables:
  #     - $DATASETS_CLI_SCHEDULER
  image: docker:latest
  services:
    - docker:dind

  tags:
    - dind
  
  script:
    # Get the latest version of NCBI's datasets-cli software
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - echo "Building $CONTAINER_IMAGE_NAME"
    - echo "docker build -f ${DATASETS_DIR}/Dockerfile --build-arg datasets_version=$DATASETS_VERSION -t $CONTAINER_IMAGE_NAME:latest $DATASETS_DIR"
    - >
      wget "https://api.github.com/repos/ncbi/datasets/releases/latest" -O - |
          grep browser_download_url |
          grep linux-amd64.cli.package.zip |
          cut -f 4 -d '"' | tee container_url.txt |
          cut -f 8 -d / > container_ver.txt
    - head container_url.txt container_ver.txt
    - echo docker build -f ${DATASETS_DIR}/Dockerfile --build-arg datasets_version=$(cat container_ver.txt) --build-arg datasets_url=$(cat container_url.txt) -t $CONTAINER_IMAGE_NAME:$(cat container_ver.txt) $DATASETS_DIR
    - docker build -f ${DATASETS_DIR}/Dockerfile --build-arg datasets_version=$(cat container_ver.txt) --build-arg datasets_url=($cat container_url.txt) -t $CONTAINER_IMAGE_NAME:$(cat container_ver.txt) $DATASETS_DIR
    
datasets_gitlab:
  extends: datasets_docker_build
  artifacts:
    paths:
      - $DATASETS_DIR
    
  script:
  - echo -e -n "Logging into Gitlab container registry:\n$CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY\n"
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  
  - echo "Tagging GitLab Docker image"
  - echo "docker tag $CONTAINER_IMAGE_NAME:latest $CI_REGISTRY/$GITLAB_DOCKER_IMAGE:$DATASETS_VERSION"
  - echo docker tag $CONTAINER_IMAGE_NAME:latest $CI_REGISTRY/$GITLAB_DOCKER_IMAGE:$DATASETS_VERSION
  
  - echo "Pushing image to gitlab registry:"
  - echo "CMD=docker push $CI_REGISTRY/$GITLAB_DOCKER_IMAGE:$DATASETS_VERSION"
  - echo docker push "$CI_REGISTRY/$GITLAB_DOCKER_IMAGE:$DATASETS_VERSION"
  - echo docker push "$CI_REGISTRY/$GITLAB_DOCKER_IMAGE:latest"

# datasets_dockerhub:
#   extends: datasets_docker_build
#   artifacts:
#     paths:
#       - $DATASETS_DIR

#   script:
#   - echo "Logging into Dockerhub registry:"
#   - echo $ENSEMBL_DOCKERHUB_AUTH | docker login -u jalvarezjarreta --password-stdin $DHUB_REG_URL

#   - echo "Tagging Dockerhub Docker image"
#   - echo "CMD=docker tag $CONTAINER_IMAGE_NAME $DHUB_REG_URL/$DHUB_DOCKER_IMAGE:$DATASETS_VERSION"
#   - docker tag $CONTAINER_IMAGE_NAME $DHUB_REG_URL/$DHUB_DOCKER_IMAGE:$DATASETS_VERSION

#   - echo "Pushing image to dockerhub registry:"
#   - echo "CMD=docker push $DHUB_REG_URL/$DHUB_DOCKER_IMAGE:$DATASETS_VERSION"
#   - docker push "$DHUB_REG_URL/$DHUB_DOCKER_IMAGE:$DATASETS_VERSION"
