# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# License-related part of the Ensembl/ensembl-genomio CI/CD pipeline

# A generic job to be used by all License jobs with the "extends" mechanism
# (https://docs.gitlab.com/ee/ci/yaml/#extends)
.flatfile:
  stage: test
  image: python:3.11
  variables:
    CMD: python cicd/scripts/check_flatfile.py

flatfile:prepare_venv:
  extends: .flatfile
  artifacts:
    paths:
      - $RUN_DIR
  before_script:
    - python --version  # for debugging
    - python -m venv $RUN_DIR/venv
    - source $RUN_DIR/venv/bin/activate
  script:
    - pip install pyyaml

.flatfile:test:
  extends: .flatfile
  needs:
    # Using `needs` as it allows to depend on jobs from the same stage
    # (https://docs.gitlab.com/ee/ci/yaml/#needs)
    - job: flatfile:prepare_venv
      artifacts: true
  before_script:
    - source $RUN_DIR/venv/bin/activate


flatfile:json:
  extends: .flatfile:test
  script:
    - $CMD json
  only:
    changes:
      - "**/*.json"

flatfile:yaml:
  extends: .flatfile:test
  script:
    - $CMD yaml
  only:
    changes:
      - "**/*.yml"
      - "**/*.yaml"
