# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Python related part of the Ensembl/ensembl-genomio CI/CD pipeline

# Test stage instances

# A generic job to be used by all Python jobs with the "extends" mechanism
# (https://docs.gitlab.com/ee/ci/yaml/#extends)
.python:
  stage: test
  image: $PYTHON_IMAGE
  only:
    changes:
      - cicd/gitlab/parts/python.gitlab-ci.yml
      - pyproject.toml
      - "*.py"
      - src/python/**/*.py
      - scripts/**/*.py

## Prepare and load the Python virtual environment

python:prepare_venv:
  extends: .python
  artifacts:
    paths:
      - $RUN_DIR
  before_script:
    - python --version  # for debugging
    - python -m venv $RUN_DIR/venv
    - source $RUN_DIR/venv/bin/activate
  script:
    - pip install -e .[cicd]


.python:test:
  extends: .python
  needs:
    # Using `needs` as it allows to depend on jobs from the same stage
    # (https://docs.gitlab.com/ee/ci/yaml/#needs)
    - job: python:prepare_venv
      artifacts: true
  before_script:
    - source $RUN_DIR/venv/bin/activate

## Static analyses

.python:pylint:
  extends: .python:test
  variables:
    PYLINT_CMD: pylint --rcfile pyproject.toml

python:pylint:src:
  extends: .python:pylint
  script:
    - $PYLINT_CMD src/python/ensembl/io/genomio

python:pylint:tests:
  extends: .python:pylint
  script:
    - $PYLINT_CMD src/python/tests

.python:mypy:
  extends: .python:test
  variables:
    MYPY_CMD: mypy --config-file pyproject.toml

python:mypy:src:
  extends: .python:mypy
  script:
    - $MYPY_CMD src/python/ensembl/io

python:mypy:tests:
  extends: .python:mypy
  script:
    - $MYPY_CMD src/python/tests

python:black:
  extends: .python:test
  script:
    - black --config pyproject.toml --check .

## Unit tests and coverage

python:pytest:
  extends: .python:test
  script:
    - apt-get update -y
    - apt-get install -y sqlite3
    - coverage run -m pytest --junitxml=$RUN_DIR/junit_reports.xml
  artifacts:
    when: always
    reports:
      junit: $RUN_DIR/junit_reports.xml
    paths:
      - .coverage

python:coverage:
  extends: .python:test
  needs:
    # "extends" cannot merge arrays (https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#merge-details)
    - !reference [.python:test, needs]
    - job: python:pytest
      artifacts: true
  script:
    - coverage html -d $RUN_DIR/coverage
    - coverage xml -o $RUN_DIR/coverage.xml
    - genbadge coverage -i $RUN_DIR/coverage.xml -o $RUN_DIR/coverage/coverage-badge.svg
    - coverage report
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    paths:
      - $RUN_DIR/coverage


# Deploy stage instances

## Generate GitLab pages with HTML coverage report

pages:
  extends: .python
  stage: deploy
  needs:
    - job: python:coverage
      artifacts: true
  script:
    - mv $RUN_DIR/coverage/ public/
  artifacts:
    paths:
      - public
  only:
    refs:
      - main
