# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Python related part of the Ensembl/ensembl-genomio CI/CD pipeline

variables:
  # Commands for running static analyses
  PYLINT_CMD: pylint --rcfile pyproject.toml
  MYPY_CMD: mypy --config-file pyproject.toml
  BLACK_CMD: black --config pyproject.toml

# don't forget to update /pyproject.toml
#  if changing python version
image: python:3.8


# overriding the default stages list (https://docs.gitlab.com/ee/ci/yaml/#stages)
stages:
  - python:prepare_env
  - python:static_analysis
  - python:tests


# Python related environment and tests
python:prepare_env:venv:
  stage: python:prepare_env
  artifacts:
    paths:
      - $RUN_DIR
  before_script:
    - python --version # For debugging
    - python -m venv $RUN_DIR/venv
    - source $RUN_DIR/venv/bin/activate
  script:
    - pip install mypy
    - pip install types-requests  # type stub for "requests" (or run `mypy --install-types`)
    - pip install pylint
    - pip install black


##  LOCAL ENV & PIP
python:prepare_env:local:
  stage: python:prepare_env
  needs:
    # using `needs` as it allows to depend on jobs from the same stage
    #  https://docs.gitlab.com/ee/ci/yaml/#needs
    - job: python:prepare_env:venv
      artifacts: true
  artifacts:
    paths:
      - $RUN_DIR
  before_script:
    - source $RUN_DIR/venv/bin/activate
  script:
    # pip based
    - pip install -e .[dev]


##  PYTHON STATIC ANALYSIS

# A generic job to be used by various python tests
# to be reused with `extends` mechanism (https://docs.gitlab.com/ee/ci/yaml/#extends)
.python:static_analysis:generic:
  stage: python:static_analysis
  needs:
    - job: python:prepare_env:local
      artifacts: true
  before_script:
    - source $RUN_DIR/venv/bin/activate

.python:tests:generic:
  extends: .python:static_analysis:generic
  stage: python:tests


# Specific instances for static analyses
python:static_analysis:pylint:
  extends: .python:static_analysis:generic
  allow_failure: true
  script:
    - $PYLINT_CMD src/python/ensembl/io/genomio src/python/tests

python:static_analysis:mypy:src:
  extends: .python:static_analysis:generic
  script:
    - $MYPY_CMD src/python/ensembl/io

python:static_analysis:mypy:tests:
  extends: .python:static_analysis:generic
  allow_failure: true
  script:
    - $MYPY_CMD src/python/tests

python:static_analysis:black:
  extends: .python:static_analysis:generic
  allow_failure: true
  script:
    - $BLACK_CMD --verbose --check .


# Specific instances for tests
python:tests:pytest:
  extends: .python:tests:generic
  script:
    - coverage run -m pytest
    - coverage html -d $RUN_DIR/cov_report/html
    - coverage xml -o $RUN_DIR/cov_report/xml/coverage.xml
    - coverage report --format=text 2>&1 | tee $RUN_DIR/cov_report/report.txt
  # pattern to extract cov from output: https://docs.gitlab.com/ee/ci/yaml/index.html#coverage
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    #expire_in: 1 week
    paths:
      - $RUN_DIR/cov_report
    reports:
      coverage_report:
        coverage_format: cobertura
        path: $RUN_DIR/cov_report/xml/coverage.xml

